define

    suburb sub entity,
        plays me,
        plays neighbourOfMe,
        has name;

    neighbour sub relation,
        relates me,
        relates neighbourOfMe,
        has direction;

    name sub attribute,
        value string;

    direction sub attribute,
        value string;